Repository marcoglnd/mercado-fresco-packmain, pull requests merged in 2022-07, with the labels that each got.

#47 Feat: Adding new routes related to product reports
  .txt
  Makefile
  cmd/server/routes/productsRouter.go
  db/mercado_fresco.sql
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/products/controller/products.go
  internal/products/controller/products_test.go
  internal/products/domain/mocks/Repository.go
  internal/products/domain/mocks/Service.go
  internal/products/domain/product_domain.go
  internal/products/repository/mariadb/product_repository.go
  internal/products/repository/mariadb/product_repository_test.go
  internal/products/repository/mariadb/queries.go
  internal/products/service/product_service.go
  internal/products/service/product_service_test.go
  internal/products/service_test.go
  utils/random.go
  utils/randomProduct.go
Labels: development

#39 Feat: Product with implemented database connection
  .env.example
  .gitignore
  Makefile
  cmd/server/controllers/products.go
  cmd/server/handler/index_test.go
  cmd/server/handler/products_test.go
  cmd/server/main.go
  cmd/server/routes/index.go
  cmd/server/routes/productsRouter.go
  cmd/server/schemas/buyers.go
  cmd/server/schemas/employees.go
  cmd/server/schemas/index.go
  cmd/server/schemas/sections.go
  cmd/server/schemas/sellers.go
  db/database.go
  db/mercado_fresco.sql
  docker-compose.yml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  internal/products/controller/products.go
  internal/products/controller/products_test.go
  internal/products/domain/mocks/Repository.go
  internal/products/domain/mocks/Service.go
  internal/products/domain/product_domain.go
  internal/products/domain/product_errors.go
  internal/products/mocks/Repository.go
  internal/products/mocks/Service.go
  internal/products/model.go
  internal/products/repository.go
  internal/products/repository/mariadb/product_repository.go
  internal/products/repository/mariadb/product_repository_test.go
  internal/products/repository/mariadb/queries.go
  internal/products/service.go
  internal/products/service/product_service.go
  internal/products/service/product_service_test.go
  internal/products/service_test.go
  utils/random.go
  utils/randomProduct.go
Labels: code review

#46 feat: Add carriers and code refactoring
  .gitignore
  cmd/server/handler/warehouses_test.go
  cmd/server/routes/index.go
  cmd/server/routes/warehousesRouter.go
  go.mod
  internal/carriers/controller/carrier_controller.go
  internal/carriers/controller/carrier_controller_test.go
  internal/carriers/domain/domain.go
  internal/carriers/domain/model.go
  internal/carriers/domain/scheme.go
  internal/carriers/mocks/domain.go
  internal/carriers/repository/mariadb/carrier_repository.go
  internal/carriers/repository/mariadb/carrier_repository_test.go
  internal/carriers/repository/mariadb/sql_queries.go
  internal/carriers/service/carrier_service.go
  internal/carriers/service/carrier_service_test.go
  internal/warehouses/controller/warehouse_controller.go
  internal/warehouses/controller/warehouse_controller_test.go
  internal/warehouses/domain/domain.go
  internal/warehouses/domain/model.go
  internal/warehouses/domain/scheme.go
  internal/warehouses/mocks/domain.go
  internal/warehouses/mocks/repository_mock.go
  internal/warehouses/mocks/service_mock.go
  internal/warehouses/model.go
  internal/warehouses/repository.go
  internal/warehouses/repository/mariadb/sql_queries.go
  internal/warehouses/repository/mariadb/warehouse_repository.go
  internal/warehouses/repository/mariadb/warehouse_repository_test.go
  internal/warehouses/scheme.go
  internal/warehouses/service.go
  internal/warehouses/service/warehouse_service.go
  internal/warehouses/service/warehouse_service_test.go
  internal/warehouses/service_test.go
  utils/random_carrier.go
  utils/random_warehouse.go
Labels: code review

#56 feat: Add reportCarriers route
  cmd/server/routes/carriersRouter.go
  cmd/server/routes/index.go
  cmd/server/routes/warehousesRouter.go
  internal/carriers/controller/carrier_controller.go
  internal/carriers/controller/carrier_controller_test.go
  internal/carriers/domain/domain.go
  internal/carriers/domain/model.go
  internal/carriers/mocks/domain.go
  internal/carriers/repository/mariadb/carrier_repository.go
  internal/carriers/repository/mariadb/carrier_repository_test.go
  internal/carriers/repository/mariadb/sql_queries.go
  internal/carriers/service/carrier_service.go
  internal/carriers/service/carrier_service_test.go
  internal/warehouses/repository/mariadb/sql_queries.go
  internal/warehouses/repository/mariadb/warehouse_repository.go
  internal/warehouses/repository/mariadb/warehouse_repository_test.go
  utils/random_carrier.go
Labels: enhancement, code review

#58 Feature/create inbound orders
  cmd/server/handler/index_test.go
  cmd/server/handler/section_test.go
  cmd/server/handler/sellers_test.go
  cmd/server/routes/employees_router.go
  cmd/server/routes/inbound_order_router.go
  cmd/server/routes/index.go
  db/mercado_fresco.sql
  docker-compose.yml
  go.mod
  internal/employees/controller/employee_controller.go
  internal/employees/controller/employee_controller_test.go
  internal/employees/domain/employee_domain.go
  internal/employees/domain/employee_errors.go
  internal/employees/domain/employee_model.go
  internal/employees/domain/mocks/EmployeeRepository.go
  internal/employees/domain/mocks/EmployeeService.go
  internal/employees/repository/mariadb/employee_repository.go
  internal/employees/repository/mariadb/employee_repository_test.go
  internal/employees/repository/mariadb/queries.go
  internal/employees/service/employee_service.go
  internal/employees/service/employee_service_test.go
  internal/inbound_orders/controller/inbound_order_controller.go
  internal/inbound_orders/controller/inbound_order_controller_test.go
  internal/inbound_orders/domain/inbound_order_domain.go
  internal/inbound_orders/domain/inbound_order_errors.go
  internal/inbound_orders/domain/inbound_order_model.go
  internal/inbound_orders/domain/mocks/InboundOrderRepository.go
  internal/inbound_orders/domain/mocks/InboundOrderService.go
  internal/inbound_orders/repository/mariadb/inbound_order_repository.go
  internal/inbound_orders/repository/mariadb/inbound_order_repository_test.go
  internal/inbound_orders/repository/mariadb/queries.go
  internal/inbound_orders/service/inbound_order_service.go
  internal/inbound_orders/service/inbound_order_service_test.go
  utils/ramdom_employee.go
  utils/ramdom_inbound_order.go
Labels: code review

#44 refatoração seller
  .DS_Store
  cmd/server/controllers/sellers.go
  cmd/server/routes/index.go
  cmd/server/routes/localitiesRouter.go
  cmd/server/routes/sellersRouter.go
  db/database.go
  db/mercado_fresco.sql
  internal/localities/controller/localities_controller.go
  internal/localities/controller/localities_controller_test.go
  internal/localities/domain/localities_domain.go
  internal/localities/domain/localities_errors.go
  internal/localities/domain/mocks/LocalityRepository.go
  internal/localities/domain/mocks/LocalityService.go
  internal/localities/repository/mariadb/localities_repository.go
  internal/localities/repository/mariadb/localities_repository_test.go
  internal/localities/repository/mariadb/queries.go
  internal/localities/service/localities_service.go
  internal/localities/service/service_test.go
  internal/sellers/controller/sellers_controller.go
  internal/sellers/controller/sellers_controller_test.go
  internal/sellers/domain/mocks/SellerRepository.go
  internal/sellers/domain/mocks/SellerService.go
  internal/sellers/domain/sellers_domain.go
  internal/sellers/domain/sellers_errors.go
  internal/sellers/mocks/Repository.go
  internal/sellers/mocks/Service.go
  internal/sellers/model.go
  internal/sellers/repository.go
  internal/sellers/repository/mariadb/queries.go
  internal/sellers/repository/mariadb/sellers_repository.go
  internal/sellers/repository/mariadb/sellers_repository_test.go
  internal/sellers/service.go
  internal/sellers/service/sellers_service.go
  internal/sellers/service/service_test.go
  internal/sellers/service_test.go
  utils/randomLocality.go
  utils/randomSeller.go
Labels: code review

#60 Refac tests get qty of records
  cmd/server/routes/products_router.go
  internal/products/controller/products.go
  internal/products/controller/products_test.go
Labels: code review

#57 Refact - Section db connect
  .env.example
  .gitignore
  cmd/server/routes/index.go
  cmd/server/routes/products_router.go
  cmd/server/routes/sectionsRouter.go
  db/mercado_fresco.sql
  internal/products/controller/products.go
  internal/products/controller/products_test.go
  internal/products/domain/mocks/Repository.go
  internal/products/domain/mocks/Service.go
  internal/products/domain/product_domain.go
  internal/products/repository/mariadb/product_repository.go
  internal/products/repository/mariadb/product_repository_test.go
  internal/products/repository/mariadb/queries.go
  internal/products/service/product_service.go
  internal/products/service/product_service_test.go
  internal/sections/controller/section_test.go
  internal/sections/controller/sections.go
  internal/sections/domain/mocks/Repository.go
  internal/sections/domain/mocks/Service.go
  internal/sections/domain/section_domain.go
  internal/sections/domain/section_errors.go
  internal/sections/mocks/Repository.go
  internal/sections/mocks/Service.go
  internal/sections/model.go
  internal/sections/repository.go
  internal/sections/repository/mariadb/queries.go
  internal/sections/repository/mariadb/section_repository.go
  internal/sections/repository/mariadb/section_repository_test.go
  internal/sections/service.go
  internal/sections/service/section_service.go
  internal/sections/service/section_service_test.go
  internal/sections/service_test.go
  utils/random_product.go
  utils/random_section.go
Labels: code review

#70 fix swags round 3
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/buyers/controller/buyer_controller.go
  internal/employees/controller/employee_controller.go
  internal/employees/repository/mariadb/employee_repository.go
  internal/employees/service/employee_service.go
  utils/ramdom_employee.go
Labels: code review
